### PR TITLE
Support Odroid C4 SBC

### PR DESCRIPTION
**Pull request by ubergeek801**
This PR is supplemental to https://github.com/home-assistant/operating-system/pull/926, which adds support for the Odroid C4 SBC to HassOS.

The C4's u-boot configuration is very similar to the N2's. For the N2, the blobs `acs.bin` and `bl301.bin` are provided in this repo, and the C4 build, once finalized, will expect the same.

The blobs in this PR were built by myself from https://github.com/hardkernel/u-boot. If you trust them, they can be used directly; alternatively, they could also be obtained from a more reputable source such as https://gitlab.com/superna9999/amlogic-boot-fip, a repository controlled by Neil Armstrong who is well-known in the Amlogic open-source community.

### CODE REVIEW

**Comment by agners** [comment]
Since we reuse the shell script for the two boards, I suggest to create a directory `hardkernel`, and then store `blx_fix_g12a.sh` shell script there. E.g.

```
hardkernel/blx_fix_g12a.sh
hardkernel/odroid-n2/..
hardkernel/odroid-c4/..
```

**Comment by ubergeek801** [comment]
> Since we reuse the shell script for the two boards, I suggest to create a directory `hardkernel`, and then store `blx_fix_g12a.sh` shell script there. E.g. ...

I'd be happy to make those changes here, although that will break `operating-system` unless home-assistant/operating-system#926 is merged at the same time.

**Comment by pvizeli** [comment]
Nope, we use commits

**Comment by ubergeek801** [comment]
@pvizeli I'm still not clear about what I should do. If you wish, I will make @agners ' suggested change here, and also update the 926 PR for both the N2 and C4 builds to use the updated locations.

**Comment by ubergeek801** [comment]
I see what you mean now; in `operating-system` the commit IDs are referenced directly, rather than any specific branch. So I guess once this PR is merged, I'll be able to update #926. Meanwhile, I've made the changes suggested by @agners. Thanks!

**Review by pvizeli — APPROVED** [review]

**Comment by chrismade** [comment]
I'm also interested in Odroid C4 support for HA/OS ... trying to understand if / how I can support here - I understand work has just started ... and I see a stop in building the OS at a very eary stage with message:
```
>>>   Executing post-image script /build/buildroot-external/scripts/post-image.sh
cp: cannot stat '/build/buildroot/output/images/meson-sm1-odroid-c4.dtb': No such file or directory
```

**Pull request merged**
